### ISSUE TITLE
Various issues and several notes

### ISSUE THREAD

**Issue by ayblanchet** [microsoft/Odyss-e-de-Teams#11]
Hi,

I could be run application after any changes:
**In azure aad:** 
- Expose an api:
   - api://{APP_SERVER_URL}/{TENANT_ID}
   - Authorise client application: 1fec8e78-bce4-4aaf-ab1b-5451cc387264 (teams web app) and 5e3ce6c0-2b1f-4285-8d4b-75ee78787346 (teams desktop)

**In app server :**
   - Add all configuration keys from docker-compose.yml in app server configuration (API_URL, STATIC_URL, AZUREAD_APPLICATION_ID, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, AZUREAD_BaseUri ...) 

**In source code:**
- Replace your tenant tag etc.. in all files:
  - adal.auth.service.js
  - msal.auth.service.js
  - teams.auth.service.js
- Change valid domain in manifest.json
- Copy .env and/or .env.production and fill environment variables in client folder and rebuild client
- In crypto.js: 
 **const key = crypto.scryptSync(CRYPTO_SECRET_KEY, 'salt', 32);**
 ...
 const cipher = crypto.createCipheriv(CRYPTO_ALGORITHM, **key**, iv);
- Clarification: Only prod folder must be deploy in app server

**In database:** 
Missing data for :
- t_semaine
- t_thematique
- j_organisation_agenda
- j_organisation_semaine

Missing assets from t_questions (PILPROJ/ ... )

After all changes I have always on error with cookies. Cookies.set() js function not create cookie in Teams Web app (it works on teams desktop) and the application cannot be get user with /user api. 

Can you help me on this issue?

Best regards,

**Comment by matthieugi** [comment]
Hi, this should be addressed by latest release
