### ISSUE TITLE
Where is the folder Odyssee_teams_pub ?

### ISSUE THREAD

**Issue by jjabewe** [microsoft/Odyss-e-de-Teams#17]
Hi,
On the step 38, we need open the folder Odyssee_teams_pub with VSC, but where is it ?

When I run "npm i", I obtain some errors.

npm WARN deprecated eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated html-webpack-plugin@4.0.0-beta.11: please switch to a stable version
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\JonathanJACQUET\\OneDrive - BEWE\\Documents\\Odyssee\\Odysse_Teams_pub\\client\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.2.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:387:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JonathanJACQUET\\OneDrive - BEWE\\Documents\\Odyssee\\Odysse_Teams_pub\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\JonathanJACQUET\OneDrive - BEWE\Documents\Odyssee\Odysse_Teams_pub\client\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:

Could you help me ?

**Comment by matthieugi** [comment]
Hi, we updated the doc to be more precise on the topic. You should clone this repository and install dependencies in the downloaded repo.
